<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CarsTableSeeder extends Seeder
{
    public function run()
    {
        DB::table('cars')->insert([
            [
                'id' => 1,
                'brand' => 'BMW',
                'model' => 'X7 40i',
                'engine' => '3.0L',
                'price_per_day' => 230.00,
                'image' => '/images/cars/BMW_X7_40i.jpg',
                'quantity' => 1,
                'status' => 'Available',
                'reduce' => 30,
                'stars' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'brand' => 'BMW',
                'model' => 'XM',
                'engine' => '4.4L',
                'price_per_day' => 230.00,
                'image' => '/images/cars/BMW_XM.jpg',
                'quantity' => 1,
                'status' => 'Available',
                'reduce' => 30,
                'stars' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'brand' => 'BMW',
                'model' => '520i 2024 new grey',
                'engine' => '2.0L',
                'price_per_day' => 230.00,
                'image' => '/images/cars/BMW_520i_2024_new_grey.jpg',
                'quantity' => 1,
                'status' => 'Available',
                'reduce' => 30,
                'stars' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'brand' => 'BMW',
                'model' => 'M8 Competition',
                'engine' => '4.4L',
                'price_per_day' => 230.00,
                'image' => '/images/cars/BMW_M8_Competition.jpg',
                'quantity' => 1,
                'status' => 'Available',
                'reduce' => 30,
                'stars' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'brand' => 'BMW',
                'model' => '520i 2024 new black',
                'engine' => '2.0L',
                'price_per_day' => 230.00,
                'image' => '/images/cars/BMW_520i_2024_new_black.jpg',
                'quantity' => 1,
                'status' => 'Available',
                'reduce' => 30,
                'stars' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'brand' => 'Mercedes',
                'model' => 'G63 AMG',
                'engine' => '4.0L',
                'price_per_day' => 230.00,
                'image' => '/images/cars/Mercedes_G63_AMG.jpg',
                'quantity' => 1,
                'status' => 'Available',
                'reduce' => 30,
                'stars' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 7,
                'brand' => 'Cadillac',
                'model' => 'Escalade',
                'engine' => '6.2L',
                'price_per_day' => 230.00,
                'image' => '/images/cars/Cadillac_Escalade.jpg',
                'quantity' => 1,
                'status' => 'Available',
                'reduce' => 30,
                'stars' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 8,
                'brand' => 'BMW',
                'model' => '430i Cabrio',
                'engine' => '2.0L',
                'price_per_day' => 230.00,
                'image' => '/images/cars/BMW_430i_Cabrio.jpg',
                'quantity' => 1,
                'status' => 'Available',
                'reduce' => 30,
                'stars' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
